
coach_to_image = {
        'Paulo Bento': 'images/coaches/paulo_bento.jpg',
        'Marcelo Bielsa': 'images/coaches/marcelo_bielsa.jpg',
        'Nenad Bjelica': 'images/coaches/nenad_bjelica.jpg',
        'Mathias de Boer': 'images/coaches/mathias_de_boer.jpg',
        'Zbigniew Boniek': 'images/coaches/zibi_top.jpg',
        'Steven Gerrard': 'images/coaches/steven_gerrard.jpg',
        'Avram Grant': 'images/coaches/avram_grant.jpg',
        'Pep Guardiola': 'images/coaches/pep_guardiola.jpg',
        'Tomasz Hajto': 'images/coaches/tomasz_hajto.jpg',
        'Thierry Henry': 'images/coaches/thierry_henry.jpg',
        'Henryk Kasperczak': 'images/coaches/henryk_kasperczak.jpg',
        'Roman Kołtoń': 'images/coaches/roman_kolton.jpg',
        'Wojciech Kowalczyk': 'images/coaches/wojciech_kowalczyk.jpg',
        'Stanislav Levy': 'images/coaches/stanislav_levy.jpg',
        'Joachim Löw': 'images/coaches/joachim_loew.jpg',
        'Peter Nowak': 'images/coaches/peter_nowak.jpg',
        'Marek Papszun': 'images/coaches/marek_papszun.jpg',
        'Vladimir Petković': 'images/coaches/vladimir_petkovic.jpg',
        'Robort Podoliński': 'images/coaches/robert_podolinski.jpg',
        'Michał Probierz': 'images/coaches/michal_probierz.jpg',
        'Herve Renard': 'images/coaches/herve_renard.jpg',
        'Fernando Santos': 'images/coaches/fernando_santos.jpg',
        'Piotr Stokowiec': 'images/coaches/piotr_stokowiec.jpg',
        'Andrij Szewczenko': 'images/coaches/andrij_szewczenko.jpg',
        'Thomas Tuchel': 'images/coaches/thomas_tuchel.jpg',
        'Jan Urban': 'images/coaches/jan_urban.jpg',
        'Zinedine Zidane': 'images/coaches/zinedine_zidane.jpg',
        'Dziki Trener': 'images/coaches/dziki_trener.jpg',
        'Fernando Santos!': 'images/coaches/fernando_santos!.jpg',
        'Vladimir Petković!': 'images/coaches/vladimir_petkovic!.jpg',
        'Ricardo Sá Pinto': 'images/coaches/ricardo_sa_pinto.jpg',
}